"""Added new fields concerning references to Application model.

Revision ID: fcf45794ca8b
Revises: 
Create Date: 2025-02-23 23:33:37.737396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcf45794ca8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('app_is_accepted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ref_is_accepted', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_accepted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_accepted', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('ref_is_accepted')
        batch_op.drop_column('app_is_accepted')

    # ### end Alembic commands ###
